### ISSUE TITLE
PyQt5 GUI curve and surface fitter

### ISSUE THREAD

**Issue by zunzun** [royabouhamad/PyQt5-Calculator#1]
I saw that you are creating a pyQt5 calculator on GitHub and thought you might like to see my pyQt5 GUI graphical curve fitter and surface fitter, also on github. The matplotlib 3D surface plots of the fitted equations look really cool. My background is in nuclear engineering and industrial radiation physics, and I love Python, so please let me know if you have any questions.

The URL on github is https://github.com/zunzun/pyQt5Fit

James Phillips

**Comment by royabouhamad** [comment]
Hey James,
That looks pretty cool. Just wondering, how did you find my repository, was it through my blog or a github search? Also how experienced are you with PyQt5 because I'm currently trying to find a way to do something and thought you may know.
Thanks,
Roy

**Comment by royabouhamad** [comment]
@zunzun

**Comment by zunzun** [comment]
A) Found by GitHub search.

B) I have enough experience in pyQt5 to make a graphical curve fitting and surface fitting application. How might I help?

James

**Comment by royabouhamad** [comment]
I'm currently looking to find a way so that a user can upload an image to my program from the GUI and the program displays the image as well as receiving the images path so I can then feed it into my image classifier.

**Comment by zunzun** [comment]
A file selector for files located on the hard drive of the same computer that is running the GUI program?

**Comment by royabouhamad** [comment]
Yep, its supposed to allow users to select a jpg file and load the image as well as store the files path.

**Comment by zunzun** [comment]
https://pythonspot.com/en/pyqt5-file-dialog/ seems to be what you are looking for.

**Comment by mohan143341** [comment]
calculato will not work after pressing equals

**Comment by zunzun** [comment]
I don't know.
